version: "3.8"

services:
  client:
    depends_on: 
      - api
    build: ./client
    ports:
      - 3000:3000

  api: 
    depends_on: 
      - db
    build: ./api
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/app

  db:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - app:/data/db
volumes:
  app:
